import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useContext, useState, useEffect, createContext, useMemo } from "react";
import axios from "axios";

const useTodos = () => {
  const [todos, setTodos] = useState(undefined);

  useEffect(() => {
    if (!todos) {
      axios
        .get("https://jsonplaceholder.typicode.com/todos")
        .then(({ data }) => {
          setTodos(data);
        })
        .catch(({ data }) => {
          setTodos([]);
        });
    }
  });

  return {
    todos,
    setTodos,
  };
};

// Todos Context
const TodosContext = createContext();

function useTodosContext() {
  const context = useContext(TodosContext);
  if (!context) {
    throw new Error(`useCount must be used within a CountProvider`);
  }
  return context;
}

function TodosProvider(props) {
  const { todos, setTodos } = useTodos();
  const value = useMemo(() => [todos, setTodos], [todos]);
  return <TodosContext.Provider value={value} {...props} />;
}

function TodosComponent() {
  const [todos, setTodos] = useTodosContext();
  const increment = () => setTodos((c) => c + 1);
  return <button onClick={increment}>{JSON.stringify(todos)}</button>;
}

function TodosDisplay() {
  const [todos] = useTodosContext();
  return <div>The current todos count is {JSON.stringify(todos)}</div>;
}

export default function Todos({ data, error, loading }) {
  if (error) {
    return <p>Error: {error}</p>;
  } else if (loading) {
    return <p>Loading...</p>;
  } else if (!data) {
    return <p>No data</p>;
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Todos
          </h1>
        </main>
        <Link href="/todos">Todos</Link>
        <Link href="/">Home</Link>
        {/* <div>{JSON.stringify(data)}</div> */}

        <TodosProvider>
          <TodosDisplay />
          <TodosComponent />
        </TodosProvider>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    );
  }
}

Todos.getInitialProps = async ({ req }) => {
  let response;
  try {
    response = await axios.get("https://jsonplaceholder.typicode.com/todos");
  } catch (e) {
    return {
      data: undefined,
      error: "could not fetch data",
      loading: false,
    };
  }

  if (response.status === 200) {
    return {
      data: response.data,
      error: undefined,
      loading: false,
    };
  } else {
    return {
      data: undefined,
      error: "could not fetch data",
      loading: false,
    };
  }
};
